services:
  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo: